name: providentia
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  enough_plus: ^2.0.0
  csv: ^6.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
