---
id: 99e36072-d15c-4d55-8eed-881d6c9224be
---
sequenceDiagram
  actor Cloud Build
  actor Cloud Task
  participant Watch API
  participant Drive API
  participant Data Store API
  
  Cloud Build  -) Watch API: deploy watch api
  
  par 
    Watch API ->> Drive API: get startPageToken
  and
    Watch API ->> Data Store API: get startPageToken
  end
    Drive API -->> Watch API: startPageToken
    Data Store API -->> Watch API: startPageToken
  
  alt if both startPageTokens are not same
    Watch API ->> Cloud Task: add retry task after 5 minutes
    note left of Watch API: startPageToken mismatch<br>between Watch API and Data Store API<br>will cause data inconsistency<br>so retry after 5 minutes
    break
      Watch API -->> Cloud Build: 202 Accepted
    end
  else
    Watch API ->> Data Store API: set startPageToken
    Watch API ->> Drive API: watch drive
    Drive API -->> Watch API: expiration date
    Watch API ->> Cloud Task: add task at expiration date
    Cloud Task ->> Watch API: call watch api
  end